# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: /home/runner/work/Jest-Testing/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install
      working-directory: /home/runner/work/Jest-Testing

    - name: Grant execute permission to jest
      run: chmod +x node_modules/.bin/jest
      working-directory: /home/runner/work/Jest-Testing

    - name: Run Tests
      run: npm test
      working-directory: /home/runner/work/Jest-Testing
